### ISSUE TITLE
MD5值被截短，内存溢出。

### ISSUE THREAD

**Issue by detecyang** [youmi/SimulateIDFA#1]
我看到在MD5_16方法中，传入的是一个8字节的char型数组用于存储返回值，将result后12位存入会导致内存溢出：

_for(int i = 4; i < CC_MD5_DIGEST_LENGTH - 4; i++) {
     ret[i-4] = result[i];
}_

这个地方将MD5截短有些不太明白，是否有问题？

**Comment by detecyang** [comment]
还想问下连字符“-”的格式规则是什么

**Comment by 09jianfeng** [comment]
16位md5值取32位的中间16位。字符"-"插入是为了跟IDFA输出一致

**Comment by 09jianfeng** [comment]
16位16进制对应8个字节，不是12个。传入的是8位，你存12位，肯定就溢出了

**Comment by detecyang** [comment]
噢是我看错了，但是md5截短了会不会导致重复率增加

**Comment by 09jianfeng** [comment]
不会
