### ISSUE TITLE
calling this code multiple time on one device 

### ISSUE THREAD

**Issue by quazarteam** [youmi/SimulateIDFA#3]
Hello!

How this code supposed to generate unique id if you're using system boot time ? i suppose that every time when this code called on particular device, then different output is returned, right ?

**Comment by 09jianfeng** [comment]
System boot time will not be changed unless system reboot.

**Comment by quazarteam** [comment]
system reboot is not such a rare thing nowadays.. thanks for the buggy iOS and iPhone hardware. so, it seems like the output of this class is still not very reliable. But, we can at least save in keychains and use it on permanent basis..

**Comment by 09jianfeng** [comment]
If you want to track a device for a long time, we suggest you save idfv in keychains.  This code provide the same deviceID shared by different  APP at specific times.

**Comment by quazarteam** [comment]
that exactly my thoughts
